name: Continuous integration

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
        types: [ opened, synchronize ]

jobs:
    check:
        name: Check
        runs-on: ubuntu-latest
        permissions:
            contents: 'read'
        strategy:
            matrix:
                command: [ lint, typecheck ]
        steps:
            -   name: Checkout
                uses: actions/checkout@v5

            -   name: Setup Node.js
                uses: actions/setup-node@v4
                with:
                    node-version: '20'
                    cache: 'npm'

            -   name: Install dependencies
                run: npm install

            -   name: ${{ matrix.command }}
                run: npm run ${{ matrix.command }}
